/* This file is auto-generated by terra-dev-site's generate-component-config config. */

// Component Examples
import TerraDevSiteSiteDocTemplate from './examples/SiteDocTemplate.site-page';

// Component Test Examples
import DefaultDocSiteTemplate from './examples/test-examples/templates/DefaultDocSiteTemplate.example';

const componentConfig = {
  'terra-dev-site': {
    name: 'Dev Site',
    path: '/dev-site',
    pages: [
      {
        name: 'Site Doc Template',
        path: '/site-doc-template',
        component: TerraDevSiteSiteDocTemplate,
      },
    ],
    tests: [
      {
        name: 'Templates',
        path: '/templates',
        tests: [
          {
            name: 'Default Doc Site Template',
            path: '/default-doc-site-template',
            component: DefaultDocSiteTemplate,
          },
        ],
      },
    ],
  },
};

export default componentConfig;
